development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: todopropa_development
  pool: 5
  username: paolotax
  password: ptaxptax
  min_messages: warning

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

