require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CausaliController do

  # This should return the minimal set of attributes required to create a valid
  # Causale. As you add validations to Causale, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "causale" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CausaliController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all causali as @causali" do
      causale = Causale.create! valid_attributes
      get :index, {}, valid_session
      assigns(:causali).should eq([causale])
    end
  end

  describe "GET show" do
    it "assigns the requested causale as @causale" do
      causale = Causale.create! valid_attributes
      get :show, {:id => causale.to_param}, valid_session
      assigns(:causale).should eq(causale)
    end
  end

  describe "GET new" do
    it "assigns a new causale as @causale" do
      get :new, {}, valid_session
      assigns(:causale).should be_a_new(Causale)
    end
  end

  describe "GET edit" do
    it "assigns the requested causale as @causale" do
      causale = Causale.create! valid_attributes
      get :edit, {:id => causale.to_param}, valid_session
      assigns(:causale).should eq(causale)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Causale" do
        expect {
          post :create, {:causale => valid_attributes}, valid_session
        }.to change(Causale, :count).by(1)
      end

      it "assigns a newly created causale as @causale" do
        post :create, {:causale => valid_attributes}, valid_session
        assigns(:causale).should be_a(Causale)
        assigns(:causale).should be_persisted
      end

      it "redirects to the created causale" do
        post :create, {:causale => valid_attributes}, valid_session
        response.should redirect_to(Causale.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved causale as @causale" do
        # Trigger the behavior that occurs when invalid params are submitted
        Causale.any_instance.stub(:save).and_return(false)
        post :create, {:causale => { "causale" => "invalid value" }}, valid_session
        assigns(:causale).should be_a_new(Causale)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Causale.any_instance.stub(:save).and_return(false)
        post :create, {:causale => { "causale" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested causale" do
        causale = Causale.create! valid_attributes
        # Assuming there are no other causali in the database, this
        # specifies that the Causale created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Causale.any_instance.should_receive(:update_attributes).with({ "causale" => "MyString" })
        put :update, {:id => causale.to_param, :causale => { "causale" => "MyString" }}, valid_session
      end

      it "assigns the requested causale as @causale" do
        causale = Causale.create! valid_attributes
        put :update, {:id => causale.to_param, :causale => valid_attributes}, valid_session
        assigns(:causale).should eq(causale)
      end

      it "redirects to the causale" do
        causale = Causale.create! valid_attributes
        put :update, {:id => causale.to_param, :causale => valid_attributes}, valid_session
        response.should redirect_to(causale)
      end
    end

    describe "with invalid params" do
      it "assigns the causale as @causale" do
        causale = Causale.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Causale.any_instance.stub(:save).and_return(false)
        put :update, {:id => causale.to_param, :causale => { "causale" => "invalid value" }}, valid_session
        assigns(:causale).should eq(causale)
      end

      it "re-renders the 'edit' template" do
        causale = Causale.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Causale.any_instance.stub(:save).and_return(false)
        put :update, {:id => causale.to_param, :causale => { "causale" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested causale" do
      causale = Causale.create! valid_attributes
      expect {
        delete :destroy, {:id => causale.to_param}, valid_session
      }.to change(Causale, :count).by(-1)
    end

    it "redirects to the causali list" do
      causale = Causale.create! valid_attributes
      delete :destroy, {:id => causale.to_param}, valid_session
      response.should redirect_to(causali_url)
    end
  end

end
