require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EditoriController do

  # This should return the minimal set of attributes required to create a valid
  # Editore. As you add validations to Editore, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "nome" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EditoriController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all editori as @editori" do
      editore = Editore.create! valid_attributes
      get :index, {}, valid_session
      assigns(:editori).should eq([editore])
    end
  end

  describe "GET show" do
    it "assigns the requested editore as @editore" do
      editore = Editore.create! valid_attributes
      get :show, {:id => editore.to_param}, valid_session
      assigns(:editore).should eq(editore)
    end
  end

  describe "GET new" do
    it "assigns a new editore as @editore" do
      get :new, {}, valid_session
      assigns(:editore).should be_a_new(Editore)
    end
  end

  describe "GET edit" do
    it "assigns the requested editore as @editore" do
      editore = Editore.create! valid_attributes
      get :edit, {:id => editore.to_param}, valid_session
      assigns(:editore).should eq(editore)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Editore" do
        expect {
          post :create, {:editore => valid_attributes}, valid_session
        }.to change(Editore, :count).by(1)
      end

      it "assigns a newly created editore as @editore" do
        post :create, {:editore => valid_attributes}, valid_session
        assigns(:editore).should be_a(Editore)
        assigns(:editore).should be_persisted
      end

      it "redirects to the created editore" do
        post :create, {:editore => valid_attributes}, valid_session
        response.should redirect_to(Editore.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved editore as @editore" do
        # Trigger the behavior that occurs when invalid params are submitted
        Editore.any_instance.stub(:save).and_return(false)
        post :create, {:editore => { "nome" => "invalid value" }}, valid_session
        assigns(:editore).should be_a_new(Editore)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Editore.any_instance.stub(:save).and_return(false)
        post :create, {:editore => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested editore" do
        editore = Editore.create! valid_attributes
        # Assuming there are no other editori in the database, this
        # specifies that the Editore created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Editore.any_instance.should_receive(:update_attributes).with({ "nome" => "MyString" })
        put :update, {:id => editore.to_param, :editore => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested editore as @editore" do
        editore = Editore.create! valid_attributes
        put :update, {:id => editore.to_param, :editore => valid_attributes}, valid_session
        assigns(:editore).should eq(editore)
      end

      it "redirects to the editore" do
        editore = Editore.create! valid_attributes
        put :update, {:id => editore.to_param, :editore => valid_attributes}, valid_session
        response.should redirect_to(editore)
      end
    end

    describe "with invalid params" do
      it "assigns the editore as @editore" do
        editore = Editore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Editore.any_instance.stub(:save).and_return(false)
        put :update, {:id => editore.to_param, :editore => { "nome" => "invalid value" }}, valid_session
        assigns(:editore).should eq(editore)
      end

      it "re-renders the 'edit' template" do
        editore = Editore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Editore.any_instance.stub(:save).and_return(false)
        put :update, {:id => editore.to_param, :editore => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested editore" do
      editore = Editore.create! valid_attributes
      expect {
        delete :destroy, {:id => editore.to_param}, valid_session
      }.to change(Editore, :count).by(-1)
    end

    it "redirects to the editori list" do
      editore = Editore.create! valid_attributes
      delete :destroy, {:id => editore.to_param}, valid_session
      response.should redirect_to(editori_url)
    end
  end

end
