require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Propa2014sController do

  # This should return the minimal set of attributes required to create a valid
  # Propa2014. As you add validations to Propa2014, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "cliente_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Propa2014sController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all propa2014s as @propa2014s" do
      propa2014 = Propa2014.create! valid_attributes
      get :index, {}, valid_session
      assigns(:propa2014s).should eq([propa2014])
    end
  end

  describe "GET show" do
    it "assigns the requested propa2014 as @propa2014" do
      propa2014 = Propa2014.create! valid_attributes
      get :show, {:id => propa2014.to_param}, valid_session
      assigns(:propa2014).should eq(propa2014)
    end
  end

  describe "GET new" do
    it "assigns a new propa2014 as @propa2014" do
      get :new, {}, valid_session
      assigns(:propa2014).should be_a_new(Propa2014)
    end
  end

  describe "GET edit" do
    it "assigns the requested propa2014 as @propa2014" do
      propa2014 = Propa2014.create! valid_attributes
      get :edit, {:id => propa2014.to_param}, valid_session
      assigns(:propa2014).should eq(propa2014)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Propa2014" do
        expect {
          post :create, {:propa2014 => valid_attributes}, valid_session
        }.to change(Propa2014, :count).by(1)
      end

      it "assigns a newly created propa2014 as @propa2014" do
        post :create, {:propa2014 => valid_attributes}, valid_session
        assigns(:propa2014).should be_a(Propa2014)
        assigns(:propa2014).should be_persisted
      end

      it "redirects to the created propa2014" do
        post :create, {:propa2014 => valid_attributes}, valid_session
        response.should redirect_to(Propa2014.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved propa2014 as @propa2014" do
        # Trigger the behavior that occurs when invalid params are submitted
        Propa2014.any_instance.stub(:save).and_return(false)
        post :create, {:propa2014 => { "cliente_id" => "invalid value" }}, valid_session
        assigns(:propa2014).should be_a_new(Propa2014)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Propa2014.any_instance.stub(:save).and_return(false)
        post :create, {:propa2014 => { "cliente_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested propa2014" do
        propa2014 = Propa2014.create! valid_attributes
        # Assuming there are no other propa2014s in the database, this
        # specifies that the Propa2014 created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Propa2014.any_instance.should_receive(:update_attributes).with({ "cliente_id" => "1" })
        put :update, {:id => propa2014.to_param, :propa2014 => { "cliente_id" => "1" }}, valid_session
      end

      it "assigns the requested propa2014 as @propa2014" do
        propa2014 = Propa2014.create! valid_attributes
        put :update, {:id => propa2014.to_param, :propa2014 => valid_attributes}, valid_session
        assigns(:propa2014).should eq(propa2014)
      end

      it "redirects to the propa2014" do
        propa2014 = Propa2014.create! valid_attributes
        put :update, {:id => propa2014.to_param, :propa2014 => valid_attributes}, valid_session
        response.should redirect_to(propa2014)
      end
    end

    describe "with invalid params" do
      it "assigns the propa2014 as @propa2014" do
        propa2014 = Propa2014.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Propa2014.any_instance.stub(:save).and_return(false)
        put :update, {:id => propa2014.to_param, :propa2014 => { "cliente_id" => "invalid value" }}, valid_session
        assigns(:propa2014).should eq(propa2014)
      end

      it "re-renders the 'edit' template" do
        propa2014 = Propa2014.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Propa2014.any_instance.stub(:save).and_return(false)
        put :update, {:id => propa2014.to_param, :propa2014 => { "cliente_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested propa2014" do
      propa2014 = Propa2014.create! valid_attributes
      expect {
        delete :destroy, {:id => propa2014.to_param}, valid_session
      }.to change(Propa2014, :count).by(-1)
    end

    it "redirects to the propa2014s list" do
      propa2014 = Propa2014.create! valid_attributes
      delete :destroy, {:id => propa2014.to_param}, valid_session
      response.should redirect_to(propa2014s_url)
    end
  end

end
